"""Generate human-readable Rust v9→v10 mapping tables from the upstream C++ source.

This is intentionally NOT used at build time.

The Rust port vendors the mapping entries into source control so the crate builds
without requiring the upstream C++ repo.

Usage (from repo root):
    python tools/gen_v9_to_v10_maps.py

You can also override paths:
    python tools/gen_v9_to_v10_maps.py --cpp path/to/PatchVersion9to10.cpp \
        --out crates/gb-save-polished/src/migrations/v9_to_v10_maps_data.rs
"""

from __future__ import annotations

import argparse
import pathlib
import re
from dataclasses import dataclass
from typing import List


REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
DEFAULT_CPP = (
    REPO_ROOT
    / "third_party"
    / "polished-save-patcher"
    / "src"
    / "patching"
    / "PatchVersion9to10.cpp"
)
DEFAULT_OUT = (
    REPO_ROOT
    / "crates"
    / "gb-save-polished"
    / "src"
    / "migrations"
    / "v9_to_v10_maps_data.rs"
)


@dataclass(frozen=True)
class MapSpec:
    rust_name: str
    cpp_func: str
    kind: str


SPECS: List[MapSpec] = [
    MapSpec("EVENT_FLAG", "mapV9EventFlagToV10", "u16_u16"),
]


def _find_function_block(cpp: str, func_name: str) -> str:
    m = re.search(
        rf"^[\t ]*\w[\w:<>,\t &*]*\b{re.escape(func_name)}\s*\(\s*", cpp, re.MULTILINE
    )
    if m is None:
        raise ValueError(f"Function definition {func_name} not found")

    tail = cpp[m.start() :]
    open_idx = tail.find("{")
    if open_idx < 0:
        raise ValueError(f"No '{{' found after {func_name}")

    depth = 0
    for rel, ch in enumerate(tail[open_idx:], start=open_idx):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return tail[: rel + 1]

    raise ValueError(f"Unterminated function {func_name}")


def _extract_initializer_lines(block: str) -> List[str]:
    lines: List[str] = []
    in_init = False

    init_start_re = re.compile(r"\bindexMap\b\s*=\s*\{")

    for raw in block.splitlines():
        stripped = raw.strip("\n")
        if not in_init:
            if init_start_re.search(stripped):
                in_init = True
            continue

        if stripped.strip().startswith("};"):
            break

        line = stripped.strip()
        lines.append(line)

    while lines and lines[-1] == "":
        lines.pop()

    return lines


_PAIR_RE = re.compile(
    r"^\{\s*(?P<a>[^,}]+)\s*,\s*(?P<b>[^}]+)\s*\}\s*,?\s*(?P<comment>//.*)?$"
)


def _emit_array_header(name: str, ty: str) -> List[str]:
    return [
        "#[rustfmt::skip]",
        f"pub const {name}_ENTRIES: {ty} = &[",
    ]


def _emit_array_footer() -> List[str]:
    return [
        "];",
        "",
    ]


def _emit_line(line: str, kind: str) -> str:
    if not line:
        return ""

    if line.startswith("//"):
        return line

    if kind in {"u16_u16"}:
        m = _PAIR_RE.match(line)
        if not m:
            raise ValueError(f"Unparsed pair line: {line}")

        a = m.group("a").strip()
        b = m.group("b").strip()
        comment = (m.group("comment") or "").rstrip()

        out = f"    ({a}, {b}),"
        return f"{out}  {comment}".rstrip()

    raise ValueError(f"Unknown kind: {kind}")


def generate(cpp_text: str) -> str:
    out: List[str] = []

    out.extend(
        [
            "// This file is generated by tools/gen_v9_to_v10_maps.py.",
            "//",
            "// It is vendored into the repo to preserve upstream comments/formatting and",
            "// to keep builds independent from the upstream C++ code.",
            "",
        ]
    )

    for spec in SPECS:
        block = _find_function_block(cpp_text, spec.cpp_func)
        lines = _extract_initializer_lines(block)

        if spec.kind == "u16_u16":
            out.extend(_emit_array_header(spec.rust_name, "&[(u16, u16)]"))
        else:
            raise ValueError(f"Unknown spec kind: {spec.kind}")

        for line in lines:
            out.append(_emit_line(line, spec.kind))

        out.extend(_emit_array_footer())

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cpp", type=pathlib.Path, default=DEFAULT_CPP)
    parser.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    cpp_path: pathlib.Path = args.cpp
    out_path: pathlib.Path = args.out

    cpp_text = cpp_path.read_text(encoding="utf-8")
    rust = generate(cpp_text)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rust, encoding="utf-8", newline="\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
